### ISSUE TITLE
Smaller time resolution ?

### ISSUE THREAD

**Issue by Startouf** [jlokimlin/cpu_timer#1]
Is it possible to use smaller time resolutions ? I am trying to use this timer on some very small code, the execution time displays lots of 0 instead of meaningful values. (Of course, I could just loop and divide, but I will get some noise)

```
call timer%start()
! fast_code
call timer%stop()
```

**Comment by jlokimlin** [comment]
`CpuTimer` supports micro-second precision as of commit [76874a3](https://github.com/jlokimlin/cpu_timer/commit/76874a35fb3855623521fb64404183b1c4448b87). To achieve this, `CpuTimer`'s private class variables were promoted from 32 to 64 bit integer kinds. Note that if further (nano-second) precision is required, `CpuTimer` could be modified to use third party libraries that provide even larger integers.

See:
https://gcc.gnu.org/onlinedocs/gfortran/SYSTEM_005fCLOCK.html
